// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	uuid "github.com/google/uuid"
)

type Order struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Status      string
	TotalPrice  int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	CancelledAt *time.Time
}

type OrderItem struct {
	ID        uuid.UUID
	OrderID   uuid.UUID
	ProductID uuid.UUID
	Sku       string
	Quantity  int32
	UnitPrice int64
	Subtotal  int64
	CreatedAt time.Time
}

type Product struct {
	ID          uuid.UUID
	Sku         string
	Name        string
	Description string
	Price       int64
	Stock       int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID           uuid.UUID
	Name         string
	Email        string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
