// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package sqlc

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const cancelOrder = `-- name: CancelOrder :one
UPDATE orders
SET status       = 'cancelled',
    cancelled_at = now(),
    updated_at   = now()
WHERE id = $1
  AND user_id = $2
  AND status = 'pending'
RETURNING id, user_id, status, total_price, created_at, updated_at, cancelled_at
`

type CancelOrderParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) CancelOrder(ctx context.Context, arg CancelOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, cancelOrder, arg.ID, arg.UserID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const countOrdersByUser = `-- name: CountOrdersByUser :one
SELECT COUNT(*) FROM orders
WHERE user_id = $1
  AND ($2::text IS NULL OR status = $2::text)
`

type CountOrdersByUserParams struct {
	UserID uuid.UUID
	Status *string
}

func (q *Queries) CountOrdersByUser(ctx context.Context, arg CountOrdersByUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOrdersByUser, arg.UserID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (id, user_id, status, total_price)
VALUES ($1, $2, 'pending', $3)
RETURNING id, user_id, status, total_price, created_at, updated_at, cancelled_at
`

type CreateOrderParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	TotalPrice int64
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, arg.ID, arg.UserID, arg.TotalPrice)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (id, order_id, product_id, sku, quantity, unit_price, subtotal)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, order_id, product_id, sku, quantity, unit_price, subtotal, created_at
`

type CreateOrderItemParams struct {
	ID        uuid.UUID
	OrderID   uuid.UUID
	ProductID uuid.UUID
	Sku       string
	Quantity  int32
	UnitPrice int64
	Subtotal  int64
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.ID,
		arg.OrderID,
		arg.ProductID,
		arg.Sku,
		arg.Quantity,
		arg.UnitPrice,
		arg.Subtotal,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.Sku,
		&i.Quantity,
		&i.UnitPrice,
		&i.Subtotal,
		&i.CreatedAt,
	)
	return i, err
}

const decreaseProductStock = `-- name: DecreaseProductStock :execrows
UPDATE products
SET stock = stock - $1, updated_at = now()
WHERE id = $2
`

type DecreaseProductStockParams struct {
	Quantity int32
	ID       uuid.UUID
}

func (q *Queries) DecreaseProductStock(ctx context.Context, arg DecreaseProductStockParams) (int64, error) {
	result, err := q.db.Exec(ctx, decreaseProductStock, arg.Quantity, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOrderByIDForUser = `-- name: GetOrderByIDForUser :one
SELECT id, user_id, status, total_price, created_at, updated_at, cancelled_at FROM orders
WHERE id = $1 AND user_id = $2
`

type GetOrderByIDForUserParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetOrderByIDForUser(ctx context.Context, arg GetOrderByIDForUserParams) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByIDForUser, arg.ID, arg.UserID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const increaseProductStock = `-- name: IncreaseProductStock :execrows
UPDATE products
SET stock = stock + $1, updated_at = now()
WHERE id = $2
`

type IncreaseProductStockParams struct {
	Quantity int32
	ID       uuid.UUID
}

func (q *Queries) IncreaseProductStock(ctx context.Context, arg IncreaseProductStockParams) (int64, error) {
	result, err := q.db.Exec(ctx, increaseProductStock, arg.Quantity, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listOrderItemsByOrderID = `-- name: ListOrderItemsByOrderID :many
SELECT id, order_id, product_id, sku, quantity, unit_price, subtotal, created_at FROM order_items
WHERE order_id = $1
ORDER BY product_id
`

func (q *Queries) ListOrderItemsByOrderID(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.Sku,
			&i.Quantity,
			&i.UnitPrice,
			&i.Subtotal,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItemsWithProductNameByOrderIDs = `-- name: ListOrderItemsWithProductNameByOrderIDs :many
SELECT oi.id, oi.order_id, oi.product_id, oi.sku, oi.quantity, oi.unit_price, oi.subtotal, oi.created_at, p.name AS product_name
FROM order_items oi
JOIN products p ON p.id = oi.product_id
WHERE oi.order_id = ANY($1::uuid[])
ORDER BY oi.created_at, oi.id
`

type ListOrderItemsWithProductNameByOrderIDsRow struct {
	ID          uuid.UUID
	OrderID     uuid.UUID
	ProductID   uuid.UUID
	Sku         string
	Quantity    int32
	UnitPrice   int64
	Subtotal    int64
	CreatedAt   time.Time
	ProductName string
}

func (q *Queries) ListOrderItemsWithProductNameByOrderIDs(ctx context.Context, orderIds []uuid.UUID) ([]ListOrderItemsWithProductNameByOrderIDsRow, error) {
	rows, err := q.db.Query(ctx, listOrderItemsWithProductNameByOrderIDs, orderIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrderItemsWithProductNameByOrderIDsRow{}
	for rows.Next() {
		var i ListOrderItemsWithProductNameByOrderIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.Sku,
			&i.Quantity,
			&i.UnitPrice,
			&i.Subtotal,
			&i.CreatedAt,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUser = `-- name: ListOrdersByUser :many
SELECT id, user_id, status, total_price, created_at, updated_at, cancelled_at FROM orders
WHERE user_id = $1
  AND ($2::text IS NULL OR status = $2::text)
ORDER BY created_at DESC, id DESC
LIMIT $4 OFFSET $3
`

type ListOrdersByUserParams struct {
	UserID    uuid.UUID
	Status    *string
	RowOffset int32
	RowLimit  int32
}

func (q *Queries) ListOrdersByUser(ctx context.Context, arg ListOrdersByUserParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByUser,
		arg.UserID,
		arg.Status,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.TotalPrice,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CancelledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsBySKUsForUpdate = `-- name: ListProductsBySKUsForUpdate :many
SELECT id, sku, name, description, price, stock, created_at, updated_at FROM products
WHERE sku = ANY($1::text[])
ORDER BY id
FOR UPDATE
`

func (q *Queries) ListProductsBySKUsForUpdate(ctx context.Context, skus []string) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsBySKUsForUpdate, skus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Sku,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Stock,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
